### ISSUE TITLE
Request: Files renamed count

### ISSUE THREAD

**Issue by smhmd** [Gadiguibou/stdrename#10]
It would be great if the finish message would say:

```
60 files renamed.
(^ _ ^)/ See you next time!
```
Also, is the new line before the message intentional? It's a bit untidy/unsettling, imo.

**Comment by Gadiguibou** [comment]
Done :)

**Comment by smhmd** [comment]
I guess `stdrename` does not check if a file is already named with a certain case, because running a renaming command will count all files instead of the one actually renamed.

```fish
$ stdrename -k
1 files renamed in 0.000342 s. See you next time!
(^ _ ^)/
$ stdrename -k # should say 0 files, now.
1 files renamed in 0.000348 s. See you next time!
(^ _ ^)/
$ # nope.
```
What I initially had in mind suggesting this is when you rename inside a small directory but you get a huge count, after which you go "oh shit!" and vice versa. So, the feature as is serves that initial purpose. But, If checking isn't all that hard and could offer some optimization, it would make the message more concrete.

**Comment by Gadiguibou** [comment]
This has been implemented. I'm gonna release a new version in a few minutes with all the latest features.
