### ISSUE TITLE
Convert stdin to stdout

### ISSUE THREAD

**Issue by smhmd** [Gadiguibou/stdrename#14]
Consider the use of `stdrename` to convert `stdin`:
```fish
$ echo 'TEXT' | stdrename -k -
text
```

**Comment by smhmd** [comment]
I'd use this to convert things in clipboard.

**Comment by Gadiguibou** [comment]
Sorry for the delay. I'm back to school so I have very little time to work on side projects atm. This shouldn't take too long to implement though so I'll make sure to tackle it as soon as I can.
