### ISSUE TITLE
Feature request: provide binaries that don't depend on glibc 2.18

### ISSUE THREAD

**Issue by Vinno97** [Gadiguibou/stdrename#21]
Hi, 

Today, I tried running stdrename on a system that does not have glibc (or at least not 2.18+) installed. 
It gives me the following error:
```
/stdrename: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by ./stdrename) 
```
I never knew it, but this is something that affects almost everything that's built with rust. 

You can  statically link MUSL to make the program not rely on glibc, or compile with a really old version since glibc is forward-compatible.
https://saarw.github.io/dev/2020/06/18/shipping-linux-binaries-that-dont-break-with-rust.html

It would be great if this could be incorporated, so `stdrename` can be a truly "it just runs" binary.

--- 

Off-topic: This great tool has been a very helpful tool in my Linux toolbelt for a while. It's so simple, yet so perfect for everything I need it for (well, until today ofc).

**Comment by Gadiguibou** [comment]
Wow! Thank you so much for this thoughtful comment and well-researched feature request. :smiley: 

I'll make sure to work on this, this week, as soon as I have some free time from uni.

I didn't know if this tool found much use with others so I stopped working on it after starting uni this fall. I'm considering refactoring the code (since it's kind of a mess still) and adding a confirmation message to preview changes (optional). Hope this helps!

**Comment by Gadiguibou** [comment]
I compiled a binary of v1.3.0 using [rust-musl-builder](https://github.com/emk/rust-musl-builder) and tested it in an Alpine Linux container.

I'll probably add this to Travis CI once I get started working on this project again.

In the meantime, can you tell me if the binary works for you @Vinno97?

**Comment by Vinno97** [comment]
You're fast! I'd love to test it, but where can I find that binary? I see no new commit, branch, or release.

---

Always difficult to tell how much an open source tool is used if you don't have telemetry. In my case, `stdrename` is one of those tools I have installed for those few times when I need it, right alongside little scripts like `sum` and `avg` commands that take sums or averages of inputs.

**Comment by Gadiguibou** [comment]
@Vinno97, it's under the latest release (v1.3.0) as `stdrename-musl`.

**Comment by Gadiguibou** [comment]
That's great to hear!
