### ISSUE TITLE
Global config

### ISSUE THREAD

**Issue by smhmd** [Gadiguibou/stdrename#3]
A global ignore file (`~/.config/stdrename/ignore`) would be great.

**Comment by Gadiguibou** [comment]
Sounds easy enough to implement with the current config crate. Will take a look at that tomorrow.

**Comment by Gadiguibou** [comment]
I've created a new branch to work on that one since it seems to be more complex than I thought. If you want you can make a pull request to accelerate that process a bit. I only work on this project as a past-time right now.

**Comment by smhmd** [comment]
Sadly, I'm not a Rust developer. Unless you want the PR in three months.

**Comment by Gadiguibou** [comment]
No worries then it'll be ready in due time
