### ISSUE TITLE
Ignore directory with based on their content/ignore git repo directories

### ISSUE THREAD

**Issue by smhmd** [Gadiguibou/stdrename#4]
Instead of ignoring directories based on their name in the [ignore file](https://github.com/Gadiguibou/stdrename/issues/3), it would also be great to ignore directories based on their content. E.g., ignore all directories that have `.git`/`node_modules` even if you're renaming recursively. (I lost unpushed git commits to this once :cry: RIP in peace.)

If this would be too complicated for nothing, an option to never rename git directories would suffice, I think.

**Comment by Gadiguibou** [comment]
Will take a look a that tomorrow. It sounds serious if you lost some git commits...

**Comment by smhmd** [comment]
It was my fault, tbh. Thanks mate. Do you think caching the directory tree in a `mktemp` file in order to be able to revert changes would be too much? One should be cautious with bulk actions either way.

**Comment by Gadiguibou** [comment]
That was one of my first ideas with this project as I don't quite like the idea of bulk irreversible actions. However, I'm not familiar with mktemp files so I'll have to read on it a bit first.

**Comment by Gadiguibou** [comment]
This version now supports all git ignore rules if the directory is a git repository. Please tell me if that does the trick.

**Comment by smhmd** [comment]
Good one!
